"""slot_60

Revision ID: 1b2e4535aed8
Revises: 30d6e6b62522
Create Date: 2022-03-16 12:30:15.923388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2e4535aed8'
down_revision = '30d6e6b62522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'days_10', 'slot_60', ['slot'], ['slot'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'days_10', type_='foreignkey')
    # ### end Alembic commands ###
