"""all

Revision ID: 30d6e6b62522
Revises: 
Create Date: 2022-03-16 12:27:48.449806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d6e6b62522'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_30',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Time(), nullable=False),
    sa.Column('booked', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot')
    )
    op.create_foreign_key(None, 'days_10', 'slot_30', ['slot'], ['slot'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'slot_60', ['slot'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slot_60', type_='unique')
    op.drop_constraint(None, 'days_10', type_='foreignkey')
    op.drop_table('slot_30')
    # ### end Alembic commands ###
