"""update2

Revision ID: 4c879268c669
Revises: 641f2dfb13b0
Create Date: 2022-03-18 14:44:58.171252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c879268c669'
down_revision = '641f2dfb13b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('slots_truck_key', 'slots', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('slots_truck_key', 'slots', ['truck'])
    # ### end Alembic commands ###
