"""update1

Revision ID: 6d7ddb0b5c2a
Revises: f21aa7ee6050
Create Date: 2022-03-18 11:11:56.103453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7ddb0b5c2a'
down_revision = 'f21aa7ee6050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
