"""fkeys

Revision ID: a427bdface1d
Revises: 1b2e4535aed8
Create Date: 2022-03-17 16:25:03.376626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a427bdface1d'
down_revision = '1b2e4535aed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('slots_bay_fkey', 'slots', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('slots_bay_fkey', 'slots', 'bay', ['bay'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
