"""adding names not null

Revision ID: ad0462a5bfc2
Revises: a74250816b0f
Create Date: 2022-06-02 22:45:03.540657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0462a5bfc2'
down_revision = 'a74250816b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subadmin', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subadmin', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('admin', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
