"""update

Revision ID: f21aa7ee6050
Revises: a427bdface1d
Create Date: 2022-03-18 11:05:08.527094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21aa7ee6050'
down_revision = 'a427bdface1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bay', ['bay_name'])
    op.add_column('slots', sa.Column('bay_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'slots', 'bay', ['bay_name'], ['bay_name'], ondelete='CASCADE')
    op.drop_column('slots', 'bay')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('bay', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'slots', type_='foreignkey')
    op.drop_column('slots', 'bay_name')
    op.drop_constraint(None, 'bay', type_='unique')
    # ### end Alembic commands ###
